wechselgeld_tagesanfang: 100
employees:
  - Bitte wählen...
  - Jule
  - Carallalola
  - Anke
  - Katia
  - Alina
  - Annalena
  - Endric
  - Isabelle
  - Max
  - Leon
  - Aushilfe
denominations:
  - key: betrag_ab_100
    ui_label: ">=100€ Betrag"
    factor: 1.0
    input_placeholder: "Betrag"
  - key: scheine_50e
    ui_label: "50€ Scheine"
    factor: 50.0
  - key: scheine_20e
    ui_label: "20€ Scheine"
    factor: 20.0
  - key: scheine_10e
    ui_label: "10€ Scheine"
    factor: 10.0
  - key: scheine_5e
    ui_label: "5€ Scheine"
    factor: 5.0
  - key: muenzen_2e
    ui_label: "2€ Münzen"
    factor: 2.0
  - key: muenzen_1e
    ui_label: "1€ Münzen"
    factor: 1.0
  - key: muenzen_50ct
    ui_label: "50ct Münzen"
    factor: 0.5
  - key: muenzen_20ct
    ui_label: "20ct Münzen"
    factor: 0.2
  - key: muenzen_10ct
    ui_label: "10ct Münzen"
    factor: 0.1
